services:
  history_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: history-track
    restart: unless-stopped
    networks:
      - mon-network
    depends_on:
      - history_db
  history_db:
    image: postgres
    container_name: history_pgdb
    restart: unless-stopped
    environment:
      POSTGRES_USER: user-name
      POSTGRES_PASSWORD: strong-password
      POSTGRES_DB: history_db
    networks:
      - mon-network
    volumes:
      - local_pgdata:/var/lib/postgresql/data


volumes:
  local_pgdata:
  pgadmin-data:

networks:
  mon-network:
    driver: bridge
    external: true
